// import "./assets/images/icons/favicon.ico";
// import "./assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css";
// import "./assets/vendor/bootstrap/css/bootstrap.min.css";
// import "./assets/vendor/animate/animate.css";
// import "./assets/vendor/css-hamburgers/hamburgers.min.css";
// import "./assets/vendor/select2/select2.min.css";
// import "./assets/css/util.css";
// import "./assets/css/main.css";
import "./assets/images/icons/favicon.ico";
import "./assets/vendor/bootstrap/css/bootstrap.min.css";
import "./assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css";
import "./assets/vendor/animate/animate.css";
import "./assets/vendor/css-hamburgers/hamburgers.min.css";
import "./assets/vendor/select2/select2.min.css";
import "./assets/css/util.css";
import "./assets/css/main.css";
import "./assets/css/index.css";
import "./assets/css/index2.css";
